//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartEnergyOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarbonEmissionsRelativeMeritDataPoint
    {
        public int EmissionsRegionID { get; set; }
        public System.DateTime DateTimeUTC { get; set; }
        public Nullable<double> EmissionsRelativeMerit { get; set; }
        public Nullable<double> EmissionsRelativeMerit_Forcast { get; set; }
    
        public virtual EmissionsRegion EmissionsRegion { get; set; }
    }
}
