//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartEnergyOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketDataPoint
    {
        public int MarketRegionID { get; set; }
        public System.DateTime DateTimeUTC { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> DemandMW { get; set; }
        public Nullable<double> RenewablesPercentage { get; set; }
        public Nullable<double> WindMW { get; set; }
        public Nullable<double> WindPercentage { get; set; }
        public Nullable<double> SolarMW { get; set; }
        public Nullable<double> SolarPercentage { get; set; }
        public Nullable<double> CarbonPricePerKg { get; set; }
        public Nullable<double> RenewablesMW { get; set; }
        public bool IsForcastRow { get; set; }
    
        public virtual MarketRegion MarketRegion { get; set; }
    }
}
