//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartEnergyOM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartEnergyDatabase : DbContext
    {
        public SmartEnergyDatabase()
            : base("name=SmartEnergyDatabase")
        {
        }

        public SmartEnergyDatabase(string databaseConnectionString)
            : base(databaseConnectionString)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarbonEmissionsDataPoint> CarbonEmissionsDataPoints { get; set; }
        public virtual DbSet<EmissionsRegion> EmissionsRegions { get; set; }
        public virtual DbSet<MarketDataPoint> MarketDataPoints { get; set; }
        public virtual DbSet<MarketRegion> MarketRegions { get; set; }
        public virtual DbSet<MarketWeatherEmissionsRegionMapping> MarketWeatherEmissionsRegionMappings { get; set; }
        public virtual DbSet<WeatherDataPoint> WeatherDataPoints { get; set; }
        public virtual DbSet<WeatherRegion> WeatherRegions { get; set; }
    }
}
