//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartEnergyOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherDataPoint
    {
        public int WeatherRegionID { get; set; }
        public System.DateTime DateTimeUTC { get; set; }
        public Nullable<double> Temperature_Celcius { get; set; }
        public Nullable<double> DewPoint_Metric { get; set; }
        public Nullable<double> WindSpeed_Metric { get; set; }
        public Nullable<double> WindGust_Metric { get; set; }
        public Nullable<double> WindDirection_Degrees { get; set; }
        public Nullable<double> WindChill_Metric { get; set; }
        public Nullable<double> Visibility_Metric { get; set; }
        public Nullable<double> UVIndex { get; set; }
        public Nullable<double> Precipitation_Metric { get; set; }
        public Nullable<double> Snow_Metric { get; set; }
        public Nullable<double> Pressure_Metric { get; set; }
        public Nullable<double> Humidity_Percent { get; set; }
        public string ConditionDescription { get; set; }
        public bool IsForcastRow { get; set; }
    
        public virtual WeatherRegion WeatherRegion { get; set; }
    }
}
